### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [Kwpolska/kw.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by Kwpolska** [comment]
Done! Please mention me when you add the theme to your list.

**Comment by unixorn** [comment]
Adding your theme in https://github.com/unixorn/awesome-zsh-plugins/pull/390, let me know if you want the description changed.
